name: nf-core AWS full size tests
# This workflow is triggered on releases and pull-requests.
# It can be triggered manually with GitHub Actions workflow dispatch button.
# It runs the -profile test_full workflow with AWS Batch
on:
  release:
    types: [published]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  run-platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run AWS full tests
        run: echo "AWS full tests placeholder"
